# Generated by Django 4.2.9 on 2024-02-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transaction', to='wallet_manager.wallets')),
                ('wallet_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve_transaction', to='wallet_manager.wallets')),
            ],
        ),
    ]
