# Generated by Django 4.2.9 on 2024-02-04 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet_manager', '0002_alter_wallets_amount_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallets',
            new_name='Wallet',
        ),
    ]
